import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/login');
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้งาน' }).click();
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้งาน' }).fill('Tu1');
  await page.getByRole('textbox', { name: 'รหัสผ่าน' }).click();
  await page.getByRole('textbox', { name: 'รหัสผ่าน' }).fill('123456');
  await page.getByRole('button', { name: 'เข้าสู่ระบบ' }).click();
  await page.getByRole('button', { name: 'จัดการร้องเรียน' }).click();
  await page.getByRole('link', { name: 'รายการร้องเรียนทั้งหมด' }).click();
  await page.getByRole('textbox', { name: 'ค้นหาเรื่องร้องเรียน, เลขที่, หรือสถานที่' }).click();
  await page.getByRole('textbox', { name: 'ค้นหาเรื่องร้องเรียน, เลขที่, หรือสถานที่' }).fill('');
  await page.getByRole('button', { name: 'รอดำเนินการ' }).click();
  await page.getByRole('button', { name: 'อนุมัติรับเรื่อง' }).click();
  await page.getByRole('button', { name: 'เข้าที่ประชุม' }).click();
  await page.getByRole('button', { name: 'กำลังดำเนินการ' }).click();
  await page.getByRole('button', { name: 'แก้ไขแล้ว' }).click();
  await page.getByRole('button', { name: 'ไม่อนุมัติ' }).click();
  await page.getByRole('button', { name: 'ปิดเรื่อง' }).click();
  await page.getByRole('button', { name: 'ทั้งหมด' }).click();
  await page.getByRole('button', { name: 'ตัวกรองเพิ่มเติม' }).click();
  await page.getByRole('textbox').nth(1).fill('2026-06-02');
  await page.getByRole('textbox').nth(2).fill('2026-05-31');
  await page.getByRole('button', { name: 'ล้างตัวกรอง' }).click();
  await page.getByRole('button', { name: 'ตัวกรองเพิ่มเติม' }).click();
  await page.getByRole('button', { name: 'ย้อนหลัง 1 สัปดาห์' }).click();
  await page.getByRole('button', { name: 'ย้อนหลัง 2 สัปดาห์' }).click();
  await page.getByRole('button', { name: 'ย้อนหลัง 3 สัปดาห์' }).click();
  await page.getByRole('button', { name: 'ย้อนหลัง 1 เดือน' }).click();
  await page.getByRole('button', { name: 'ย้อนหลัง 3 เดือน' }).click();
  await page.getByRole('button', { name: 'ย้อนหลัง 6 เดือน' }).click();
  await page.getByRole('button', { name: 'ล้างตัวกรอง' }).click();
  await page.getByRole('link', { name: 'สร้างคำร้องใหม่' }).click();
  await page.getByRole('button', { name: '🏠 88/134 ไดโนเสาร์ พี่เต้' }).click();
  await page.getByRole('textbox', { name: 'เช่น น้ำรั่วซึม' }).click();
  await page.getByRole('textbox', { name: 'เช่น น้ำรั่วซึม' }).fill('ผมอยากเสี้ยงไดโนเสาร์ไทย');
  await page.getByRole('textbox', { name: 'อธิบายรายละเอียดปัญหา' }).click();
  await page.getByRole('textbox', { name: 'อธิบายรายละเอียดปัญหา' }).fill('สามารถหาได้จากไหน');
  await page.locator('div').filter({ hasText: /^📎 แนบไฟล์เอกสาร\/ รูปภาพ$/ }).click();
  await page.getByRole('textbox', { name: 'สำนักงาน' }).click();
  await page.getByRole('textbox', { name: 'สำนักงาน' }).fill('บ้าน');
  await page.getByRole('button', { name: 'บันทึกคำร้อง' }).click();
  await page.getByRole('button', { name: 'ยกเลิก' }).click();
  await page.getByRole('button', { name: 'บันทึกคำร้อง' }).click();
  await page.getByRole('button', { name: 'ยืนยัน' }).click();
  await page.getByRole('link', { name: 'สร้างคำร้องใหม่' }).click();
  await page.getByRole('button', { name: 'กรอกข้อมูลเอง' }).click();
  await page.getByRole('textbox', { name: 'ชื่อจริง' }).click();
  await page.getByRole('textbox', { name: 'ชื่อจริง' }).fill('นายโอ');
  await page.getByRole('textbox', { name: 'นามสกุล' }).click();
  await page.getByRole('textbox', { name: 'นามสกุล' }).fill('เลี้ยง');
  await page.getByRole('textbox', { name: '08x-xxx-xxxx' }).click();
  await page.getByRole('textbox', { name: '08x-xxx-xxxx' }).fill('0687541258');
  await page.getByRole('textbox', { name: 'เช่น 88/' }).click();
  await page.getByRole('textbox', { name: 'เช่น 88/' }).fill('83/96');
  await page.getByRole('textbox', { name: 'เช่น 1,' }).click();
  await page.getByRole('textbox', { name: 'เช่น 1,' }).fill('2');
  await page.getByRole('textbox', { name: 'ซอย' }).click();
  await page.getByRole('textbox', { name: 'ซอย' }).fill('3');
  await page.getByRole('textbox', { name: 'เช่น น้ำรั่วซึม' }).click();
  await page.getByRole('textbox', { name: 'เช่น น้ำรั่วซึม' }).fill('โอเลี้ยงกับข้าวแดง');
  await page.getByRole('textbox', { name: 'อธิบายรายละเอียดปัญหา' }).click();
  await page.getByRole('textbox', { name: 'อธิบายรายละเอียดปัญหา' }).fill('เขาไม่ซื้อมาให้');
  await page.getByText('📎 แนบไฟล์เอกสาร/ รูปภาพ').click();
  await page.getByRole('textbox', { name: 'สำนักงาน' }).click();
  await page.getByRole('textbox', { name: 'สำนักงาน' }).fill('บ้าน');
  await page.getByRole('combobox').selectOption('phone');
  await page.getByRole('button', { name: 'บันทึกคำร้อง' }).click();
  await page.getByRole('button', { name: 'ยืนยัน' }).click();
  await page.getByRole('link', { name: 'สร้างคำร้องใหม่' }).click();
  await page.getByRole('link', { name: 'ยกเลิก' }).click();
  await page.getByRole('link', { name: 'สร้างคำร้องใหม่' }).click();
  await page.getByRole('button', { name: 'กรอกข้อมูลเอง' }).click();
  await page.getByRole('link', { name: 'ยกเลิก' }).click();
  await page.getByRole('link', { name: 'จัดการ →' }).first().click();
  await page.getByRole('button', { name: 'อนุมัติ', exact: true }).click();
  await page.getByRole('textbox', { name: 'กรอกความเห็นคณะกรรมการ หรือเหตุผลประกอบการพิจารณา' }).click();
  await page.getByRole('textbox', { name: 'กรอกความเห็นคณะกรรมการ หรือเหตุผลประกอบการพิจารณา' }).fill('เห็นชอบ');
  await page.getByRole('textbox', { name: 'พิมพ์อัปเดตความคืบหน้าให้ลูกบ้านทราบ' }).click();
  await page.getByRole('textbox', { name: 'พิมพ์อัปเดตความคืบหน้าให้ลูกบ้านทราบ' }).fill('เข้าวาระประชุม');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'อัปเดตข้อมูล' }).click();
  await page.getByRole('link', { name: 'กลับไปหน้ารายการ' }).click();
  await page.getByRole('link', { name: 'จัดการ →' }).nth(1).click();
  await page.getByRole('link', { name: 'กลับไปหน้ารายการ' }).click();
  await page.locator('tr:nth-child(13) > td:nth-child(7) > .text-\\[\\#B31B1B\\]').click();
  await page.getByRole('button', { name: 'ไม่อนุมัติ' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'อัปเดตข้อมูล' }).click();
  await page.getByRole('link', { name: 'กลับไปหน้ารายการ' }).click();
  await page.getByRole('cell', { name: 'จัดการ →' }).first().click();
  await page.getByRole('link', { name: 'แก้ไข', exact: true }).click();
  await page.getByRole('button', { name: 'ไม่อนุมัติ' }).click();
  await page.getByRole('textbox', { name: 'เช่น น้ำรั่วซึม, ท่อระบายน้ำตัน' }).fill('โอเลี้ยงกับข้าวแดงและน้ำด้วย');
  await page.goto('http://localhost:3000/admin/complaints/51');
  await page.getByRole('button', { name: 'อนุมัติ', exact: true }).click();
  await page.getByRole('link', { name: 'แก้ไข', exact: true }).click();
  await page.getByRole('link', { name: 'ยกเลิก' }).click();
  await page.getByRole('button', { name: 'ลบ' }).click();
  await page.getByRole('button', { name: 'ยกเลิก' }).click();
  await page.getByRole('button', { name: 'ลบ' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'ยืนยันการลบ' }).click();
  await page.getByRole('link', { name: 'รอเข้าที่ประชุม' }).click();
  await page.getByRole('textbox', { name: 'ค้นหาวาระการประชุม' }).click();
  await page.getByRole('textbox', { name: 'ค้นหาวาระการประชุม' }).fill('');
  await page.getByRole('button', { name: 'พิมพ์วาระการประชุม' }).click();
  await page.getByRole('row', { name: 'เลขที่ หัวข้อ บ้านเลขที่ ชื่อลูกบ้าน สถานะ วันที่แจ้ง' }).getByRole('checkbox').check();
  await page.getByRole('main').getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('cell', { name: 'ผมจะสร้างเซ็นทรันสาขาดาวอังคาร' }).first().click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'นำเรื่องเข้าที่ประชุม' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'นำเรื่องเข้าที่ประชุม' }).click();
  await page.getByRole('link', { name: 'นำเรื่องเข้าที่ประชุม' }).click();
  await page.getByRole('textbox', { name: 'ค้นหาวาระการประชุม' }).click();
  await page.getByRole('textbox', { name: 'ค้นหาวาระการประชุม' }).fill('');
  await page.getByRole('button', { name: 'พิมพ์วาระการประชุม' }).click();
  await page.getByRole('row', { name: 'เลขที่ หัวข้อ บ้านเลขที่ ชื่อลูกบ้าน สถานะ วันที่แจ้ง' }).getByRole('checkbox').check();
  await page.getByRole('main').getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('cell', { name: 'ผมจะสร้างเซ็นทรันสาขาดาวอังคาร' }).first().click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'มติ: อนุมัติให้ดำเนินการ' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'มติ: อนุมัติให้ดำเนินการ' }).click();
  await page.getByText('88/134', { exact: true }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'มติ: ไม่อนุมัติ' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'มติ: ไม่อนุมัติ' }).click();
  await page.getByRole('link', { name: 'ติดตามการแก้ไขปัญหา' }).click();
  await page.getByRole('textbox', { name: 'ค้นหาเรื่องร้องเรียน, เลขที่, หรือสถานที่' }).click();
  await page.getByRole('textbox', { name: 'ค้นหาเรื่องร้องเรียน, เลขที่, หรือสถานที่' }).fill('');
  await page.getByRole('columnheader').filter({ hasText: /^$/ }).click();
  await page.getByRole('main').getByRole('button').filter({ hasText: /^$/ }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'พิมพ์เอกสารมอบหมายงาน' }).click();
  const page1 = await page1Promise;
  await page.goto('http://localhost:3000/admin/maintenance');
  await page.getByRole('cell', { name: 'พ.ค. 2569' }).click();
  await page.getByRole('button', { name: 'บันทึกการแก้ไขเสร็จสิ้น' }).click();
  await page.getByRole('textbox', { name: 'เช่น ทำความสะอาดพื้นที่, ตรวจสอบแล้วปกติ' }).click();
  await page.getByRole('textbox', { name: 'เช่น ทำความสะอาดพื้นที่, ตรวจสอบแล้วปกติ' }).fill('ไปหาเอาเอง');
  await page.getByRole('textbox', { name: 'เช่น 150 บาท' }).click();
  await page.getByRole('textbox', { name: 'เช่น 150 บาท' }).fill('0 บาท');
  await page.getByRole('button', { name: 'ยกเลิก' }).click();
  await page.getByRole('button', { name: 'บันทึกการแก้ไขเสร็จสิ้น' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'ยืนยันปิดงาน' }).click();
});