import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/login');
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้งาน' }).click();
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้งาน' }).fill('Tu1');
  await page.getByRole('textbox', { name: 'รหัสผ่าน' }).click();
  await page.getByRole('textbox', { name: 'รหัสผ่าน' }).fill('123456');
  await page.getByRole('button', { name: 'เข้าสู่ระบบ' }).click();
  await page.getByRole('button', { name: 'จัดการบัญชีผู้ใช้งาน' }).click();
  await page.getByRole('link', { name: 'บัญชีผู้ใช้ทั้งหมด' }).click();
  await page.getByRole('textbox', { name: 'ค้นหาชื่อ, นามสกุล หรือ' }).click();
  await page.getByRole('textbox', { name: 'ค้นหาชื่อ, นามสกุล หรือ' }).fill('');
  await page.locator('#user-role-filter').selectOption('resident');
  await page.locator('#user-role-filter').selectOption('staff');
  await page.locator('#user-role-filter').selectOption('admin');
  await page.locator('#user-role-filter').selectOption('all');
  await page.getByRole('button', { name: 'รีเฟรช' }).click();
  await page.getByRole('cell', { name: '@test_cache_1780166300934' }).click();
  await page.getByRole('cell', { name: 'ลูกบ้าน' }).first().click();
  await page.getByText('ลูกบ้าน').nth(2).click();
  await page.getByRole('cell', { name: 'T Test Cache' }).click();
  await page.getByRole('link', { name: 'ปรับสิทธิ์ผู้ใช้งาน' }).click();
  await page.getByRole('row', { name: 'ไ ไดโนเสาร์ พี่เต้ @Te_Trax' }).getByRole('combobox').selectOption('staff');
  await page.getByRole('button', { name: 'ยกเลิก' }).click();
  await page.getByRole('row', { name: 'ไ ไดโนเสาร์ พี่เต้ @Te_Trax' }).getByRole('combobox').selectOption('staff');
  await page.getByRole('button', { name: 'ยืนยัน' }).click();
  await page.locator('tr:nth-child(6) > td:nth-child(4) > .flex > .py-1\\.5').selectOption('admin');
  await page.getByRole('button', { name: 'ยกเลิก' }).click();
  await page.locator('tr:nth-child(6) > td:nth-child(4) > .flex > .py-1\\.5').selectOption('admin');
  await page.getByRole('button', { name: 'ยืนยัน' }).click();
  await page.getByRole('textbox', { name: 'ค้นหาชื่อ, นามสกุล หรือ' }).click();
  await page.getByRole('textbox', { name: 'ค้นหาชื่อ, นามสกุล หรือ' }).fill('');
  await page.locator('#user-role-filter').selectOption('resident');
  await page.locator('#user-role-filter').selectOption('staff');
  await page.locator('#user-role-filter').selectOption('admin');
  await page.locator('#user-role-filter').selectOption('all');
  await page.getByRole('button', { name: 'รีเฟรช' }).click();
  await page.getByRole('link', { name: 'ลบบัญชีผู้ใช้งาน' }).click();
  await page.getByRole('button', { name: 'ลบ' }).nth(5).click();
  await page.getByRole('button', { name: 'ยกเลิก' }).click();
  await page.getByRole('button', { name: 'ลบ' }).nth(5).click();
  await page.getByRole('button', { name: 'ลบบัญชีถาวร' }).click();
  await page.getByRole('textbox', { name: 'ค้นหาชื่อ, นามสกุล หรือ' }).click();
  await page.getByRole('textbox', { name: 'ค้นหาชื่อ, นามสกุล หรือ' }).fill('');
  await page.locator('#user-role-filter').selectOption('resident');
  await page.locator('#user-role-filter').selectOption('staff');
  await page.locator('#user-role-filter').selectOption('admin');
  await page.getByRole('button', { name: 'รีเฟรช' }).click();
  await page.locator('#user-role-filter').selectOption('all');
});