import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/login');
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้งาน' }).click();
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้งาน' }).fill('Te_Trax');
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้งาน' }).click();
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้งาน' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้งาน' }).fill('Bosszaza');
  await page.getByRole('textbox', { name: 'รหัสผ่าน' }).click();
  await page.getByRole('textbox', { name: 'รหัสผ่าน' }).fill('123456');
  await page.getByRole('button', { name: 'เข้าสู่ระบบ' }).click();
  await page.getByRole('link', { name: 'สร้างเรื่องร้องเรียน' }).click();
  await page.getByRole('button', { name: 'เลือกจากระบบ' }).click();
  await page.getByRole('textbox', { name: 'พิมพ์บ้านเลขที่ หรือ ชื่อ-นามสกุล' }).click();
  await page.getByRole('textbox', { name: 'พิมพ์บ้านเลขที่ หรือ ชื่อ-นามสกุล' }).fill('');
  await page.getByRole('button', { name: '🏠 88/134' }).click();
  await page.getByRole('textbox', { name: 'เช่น น้ำรั่วซึม' }).click();
  await page.getByRole('textbox', { name: 'เช่น น้ำรั่วซึม' }).fill('มีเมียมนุษย์ต่างดาว');
  await page.getByRole('textbox', { name: 'อธิบายรายละเอียดปัญหา' }).click();
  await page.getByRole('textbox', { name: 'อธิบายรายละเอียดปัญหา' }).fill('ผมอยากมีความฝันไปเป็นมนุษย์ต่างดาว');
  await page.locator('div').filter({ hasText: /^📎 แนบไฟล์เอกสาร\/ รูปภาพ$/ }).click();
  await page.getByRole('textbox', { name: 'สำนักงาน' }).click();
  await page.getByRole('textbox', { name: 'สำนักงาน' }).fill('บ้าน');
  await page.locator('input[name="reported_date"]').fill('2026-05-31');
  await page.getByRole('button', { name: 'บันทึกคำร้อง' }).click();
  await page.getByRole('button', { name: 'ยกเลิก' }).click();
  await page.getByRole('button', { name: 'บันทึกคำร้อง' }).click();
  await page.getByRole('button', { name: 'ยืนยัน' }).click();
  await page.getByRole('link', { name: 'สร้างเรื่องร้องเรียน' }).click();
  await page.getByRole('link', { name: 'ยกเลิก' }).click();
  await page.getByRole('link', { name: 'สร้างเรื่องร้องเรียน' }).click();
  await page.getByRole('button', { name: 'กรอกข้อมูลเอง' }).click();
  await page.getByRole('textbox', { name: 'ชื่อจริง' }).click();
  await page.getByRole('textbox', { name: 'ชื่อจริง' }).fill('คิม');
  await page.getByRole('textbox', { name: 'นามสกุล' }).click();
  await page.getByRole('textbox', { name: 'นามสกุล' }).fill('หัน');
  await page.getByRole('textbox', { name: '08x-xxx-xxxx' }).click();
  await page.getByRole('textbox', { name: '08x-xxx-xxxx' }).fill('0984531765');
  await page.getByRole('textbox', { name: 'เช่น 88/' }).click();
  await page.getByRole('textbox', { name: 'เช่น 88/' }).fill('88/5');
  await page.getByRole('textbox', { name: 'เช่น 1,' }).click();
  await page.getByRole('textbox', { name: 'เช่น 1,' }).fill('1');
  await page.getByRole('textbox', { name: 'ซอย' }).click();
  await page.getByRole('textbox', { name: 'ซอย' }).fill('3');
  await page.getByRole('textbox', { name: 'เช่น น้ำรั่วซึม' }).click();
  await page.getByRole('textbox', { name: 'เช่น น้ำรั่วซึม' }).fill('ผมโดนเกียน');
  await page.getByRole('textbox', { name: 'อธิบายรายละเอียดปัญหา' }).click();
  await page.getByRole('textbox', { name: 'อธิบายรายละเอียดปัญหา' }).fill('โดนเกียนRobox');
  await page.locator('div').filter({ hasText: /^📎 แนบไฟล์เอกสาร\/ รูปภาพ$/ }).click();
  await page.locator('div').filter({ hasText: /^สถานที่รับคำร้อง$/ }).click();
  await page.getByRole('textbox', { name: 'สำนักงาน' }).fill('บ้าน');
  await page.locator('input[name="reported_date"]').fill('2026-05-31');
  await page.getByRole('button', { name: 'บันทึกคำร้อง' }).click();
  await page.getByRole('button', { name: 'ยืนยัน' }).click();
  await page.getByRole('link', { name: 'สร้างเรื่องร้องเรียน' }).click();
  await page.getByRole('button', { name: 'กรอกข้อมูลเอง' }).click();
  await page.getByRole('link', { name: 'ยกเลิก' }).click();
});