import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  test.setTimeout(120000); // เพิ่ม Timeout เป็น 2 นาที เนื่องจากเทสต์มีหลายสเต็ปมาก
  await page.goto('http://localhost:3000/login');
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้งาน' }).click();
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้งาน' }).fill('Bosszaza');
  await page.getByRole('textbox', { name: 'รหัสผ่าน' }).click();
  await page.getByRole('textbox', { name: 'รหัสผ่าน' }).fill('123456');
  await page.getByRole('button', { name: 'เข้าสู่ระบบ' }).click();
  await page.getByRole('button', { name: 'จัดการร้องเรียน' }).click();
  await page.getByRole('link', { name: 'เรื่องร้องเรียนทั้งหมด' }).click();
  await page.getByRole('textbox', { name: 'ค้นหาเรื่องร้องเรียน, เลขที่, หรือสถานที่' }).click();
  await page.getByRole('textbox', { name: 'ค้นหาเรื่องร้องเรียน, เลขที่, หรือสถานที่' }).fill('');
  await page.getByRole('button', { name: 'ตัวกรองเพิ่มเติม' }).click();
  await page.getByRole('textbox').nth(1).fill('2026-05-31');
  await page.getByRole('textbox').nth(2).fill('2026-05-29');
  await page.getByRole('button', { name: 'ล้างตัวกรอง' }).click();
  await page.getByRole('button', { name: 'ตัวกรองเพิ่มเติม' }).click();
  await page.getByRole('button', { name: 'ย้อนหลัง 1 สัปดาห์' }).click();
  await page.getByRole('button', { name: 'ย้อนหลัง 2 สัปดาห์' }).click();
  await page.getByRole('button', { name: 'ย้อนหลัง 3 สัปดาห์' }).click();
  await page.getByRole('button', { name: 'ย้อนหลัง 1 เดือน' }).click();
  await page.getByRole('button', { name: 'ย้อนหลัง 3 เดือน' }).click();
  await page.getByRole('button', { name: 'ย้อนหลัง 6 เดือน' }).click();
  await page.getByRole('button', { name: 'ล้างตัวกรอง' }).click();
  await page.getByRole('button', { name: 'รอดำเนินการ' }).click();
  await page.getByRole('button', { name: 'อนุมัติรับเรื่อง' }).click();
  await page.getByRole('button', { name: 'เข้าที่ประชุม' }).click();
  await page.getByRole('button', { name: 'กำลังดำเนินการ' }).click();
  await page.getByRole('button', { name: 'แก้ไขแล้ว' }).click();
  await page.getByRole('button', { name: 'ไม่อนุมัติ' }).click();
  await page.getByRole('button', { name: 'ปิดเรื่อง' }).click();
  await page.getByRole('button', { name: 'ทั้งหมด' }).click();
  await page.getByRole('cell', { name: 'ทำวันนี่เสร็จเมือวาน' }).click();
  await page.getByRole('button', { name: 'ไม่อนุมัติ' }).click();
  await page.getByRole('textbox', { name: 'พิมพ์อัปเดตความคืบหน้าให้ลูกบ้านทราบ' }).fill('ทดสอบระบบไม่อนุมัติ');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'อัปเดตข้อมูล' }).click();
  await page.getByRole('link', { name: 'กลับไปหน้ารายการ' }).click();
  await page.getByRole('link', { name: 'สร้างคำร้องใหม่' }).click();
  await page.getByRole('button', { name: '🏠 88/134 ไดโนเสาร์ พี่เต้' }).click();
  await page.getByRole('textbox', { name: 'เช่น น้ำรั่วซึม' }).click();
  await page.getByRole('textbox', { name: 'เช่น น้ำรั่วซึม' }).fill('ผมจะสร้างเซ็นทรันสาขาดาวอังคาร');
  await page.getByRole('textbox', { name: 'อธิบายรายละเอียดปัญหา' }).click();
  await page.getByRole('textbox', { name: 'อธิบายรายละเอียดปัญหา' }).fill('ผมมีแผนขยายสาขาไปดวงจันทร์');
  await page.locator('div').filter({ hasText: /^📎 แนบไฟล์เอกสาร\/ รูปภาพ$/ }).click();
  await page.getByRole('textbox', { name: 'สำนักงาน' }).click();
  await page.getByRole('textbox', { name: 'สำนักงาน' }).fill('บ้าน');
  await page.locator('input[name="reported_date"]').fill('2026-05-31');
  await page.getByRole('button', { name: 'บันทึกคำร้อง' }).click();
  await page.getByRole('button', { name: 'ยกเลิก' }).click();
  await page.getByRole('button', { name: 'บันทึกคำร้อง' }).click();
  await page.getByRole('button', { name: 'ยืนยัน' }).click();
  await page.getByRole('link', { name: 'สร้างคำร้องใหม่' }).click();
  await page.getByRole('link', { name: 'ยกเลิก' }).click();
  await page.getByRole('link', { name: 'สร้างคำร้องใหม่' }).click();
  await page.getByRole('button', { name: 'กรอกข้อมูลเอง' }).click();
  await page.getByRole('textbox', { name: 'ชื่อจริง' }).click();
  await page.getByRole('textbox', { name: 'ชื่อจริง' }).fill('มีเกียร');
  await page.getByRole('textbox', { name: 'นามสกุล' }).click();
  await page.getByRole('textbox', { name: 'นามสกุล' }).fill('มีสักศรี');
  await page.getByRole('textbox', { name: '08x-xxx-xxxx' }).click();
  await page.getByRole('textbox', { name: '08x-xxx-xxxx' }).fill('087658764');
  await page.getByRole('textbox', { name: 'เช่น 88/' }).click();
  await page.getByRole('textbox', { name: 'เช่น 88/' }).fill('2');
  await page.getByRole('textbox', { name: 'เช่น 1,' }).click();
  await page.getByRole('textbox', { name: 'เช่น 1,' }).fill('1');
  await page.getByRole('textbox', { name: 'ซอย' }).click();
  await page.getByRole('textbox', { name: 'ซอย' }).fill('4');
  await page.getByRole('textbox', { name: 'เช่น 88/' }).click();
  await page.getByRole('textbox', { name: 'เช่น 88/' }).fill('22/45');
  await page.getByRole('textbox', { name: 'เช่น น้ำรั่วซึม' }).click();
  await page.getByRole('textbox', { name: 'เช่น น้ำรั่วซึม' }).fill('คนที่มีเกียร มีศักศรี ไปพร้อมกัน');
  await page.getByRole('textbox', { name: 'อธิบายรายละเอียดปัญหา' }).click();
  await page.getByRole('textbox', { name: 'อธิบายรายละเอียดปัญหา' }).fill('ผมเลือกคุณ');
  await page.locator('div').filter({ hasText: /^📎 แนบไฟล์เอกสาร\/ รูปภาพ$/ }).click();
  await page.getByRole('textbox', { name: 'สำนักงาน' }).click();
  await page.getByRole('textbox', { name: 'สำนักงาน' }).fill('บ้าน');
  await page.locator('input[name="reported_date"]').fill('2026-05-31');
  await page.getByRole('button', { name: 'บันทึกคำร้อง' }).click();
  await page.getByRole('button', { name: 'ยกเลิก' }).click();
  await page.getByRole('button', { name: 'บันทึกคำร้อง' }).click();
  await page.getByRole('button', { name: 'ยืนยัน' }).click();
  await page.getByRole('link', { name: 'สร้างคำร้องใหม่' }).click();
  await page.getByRole('button', { name: 'กรอกข้อมูลเอง' }).click();
  await page.getByRole('link', { name: 'ยกเลิก' }).click();
  await page.getByRole('link', { name: 'จัดการ →' }).nth(1).click();
  await page.getByRole('link', { name: 'แก้ไข', exact: true }).click();
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox', { name: 'อธิบายรายละเอียดปัญหาที่พบ' }).click();
  await page.getByRole('textbox', { name: 'อธิบายรายละเอียดปัญหาที่พบ' }).fill('ผมมีแผนขยายสาขาไปดวงจันทร์ผมจะให้แต่งงานกับมนุษย์ต่างดาว');
  await page.getByRole('button', { name: 'บันทึกการแก้ไข' }).click();
  await page.getByRole('button', { name: 'ยกเลิก' }).click();
  await page.getByRole('button', { name: 'บันทึกการแก้ไข' }).click();
  await page.getByRole('button', { name: 'ยืนยัน' }).click();
  await page.getByRole('link', { name: 'แก้ไข', exact: true }).click();
  await page.getByRole('link', { name: 'ยกเลิก' }).click();
  await page.getByRole('link', { name: 'กลับไปหน้ารายการ' }).click();
  await page.getByRole('cell', { name: 'จัดการ →' }).nth(1).click();
  await page.getByRole('button', { name: 'อนุมัติ', exact: true }).click();
  await page.getByRole('textbox', { name: 'กรอกความเห็นคณะกรรมการ หรือเหตุผลประกอบการพิจารณา' }).click();
  await page.getByRole('textbox', { name: 'กรอกความเห็นคณะกรรมการ หรือเหตุผลประกอบการพิจารณา' }).fill('เห็นชอบ');
  await page.getByRole('textbox', { name: 'พิมพ์อัปเดตความคืบหน้าให้ลูกบ้านทราบ' }).click();
  await page.getByRole('textbox', { name: 'พิมพ์อัปเดตความคืบหน้าให้ลูกบ้านทราบ' }).fill('พร้อมทำ');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'อัปเดตข้อมูล' }).click();
  await page.getByRole('link', { name: 'กลับไปหน้ารายการ' }).click();
  await page.locator('tbody tr').first().click();
  await page.getByRole('button', { name: 'ไม่อนุมัติ' }).click();
  await page.getByRole('textbox', { name: 'พิมพ์อัปเดตความคืบหน้าให้ลูกบ้านทราบ' }).fill('ทดสอบระบบไม่อนุมัติ 2');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'อัปเดตข้อมูล' }).click();
  await page.getByRole('link', { name: 'กลับไปหน้ารายการ' }).click();
  await page.getByRole('link', { name: 'รอเข้าที่ประชุม' }).click();
  await page.getByRole('textbox', { name: 'ค้นหาวาระการประชุม' }).click();
  await page.getByRole('textbox', { name: 'ค้นหาวาระการประชุม' }).fill('');
  await page.getByRole('button', { name: 'พิมพ์วาระการประชุม' }).click();
  await page.getByRole('columnheader').filter({ hasText: /^$/ }).click();
  await page.getByRole('main').getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByText('อนุมัติรับเรื่อง').first().click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'นำเรื่องเข้าที่ประชุม' }).click();
  await page.getByRole('cell', { name: 'อนุมัติรับเรื่อง' }).first().click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'นำเรื่องเข้าที่ประชุม' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'นำเรื่องเข้าที่ประชุม' }).click();
  await page.getByRole('main').getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByText('อนุมัติรับเรื่อง').first().click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'นำเรื่องเข้าที่ประชุม' }).click();
  await page.getByRole('link', { name: 'นำเรื่องเข้าที่ประชุม' }).click();
  await page.getByRole('textbox', { name: 'ค้นหาวาระการประชุม' }).click();
  await page.getByRole('textbox', { name: 'ค้นหาวาระการประชุม' }).fill('');
  await page.getByRole('row', { name: 'เลขที่ หัวข้อ บ้านเลขที่ ชื่อลูกบ้าน สถานะ วันที่แจ้ง' }).getByRole('checkbox').check();
  await page.getByRole('main').getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('button', { name: 'พิมพ์วาระการประชุม' }).click();
  await page.getByRole('cell', { name: '/134' }).first().click();
  await page.getByRole('main').getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('cell', { name: 'ผมจะสร้างเซ็นทรันสาขาดาวอังคาร' }).first().click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'มติ: อนุมัติให้ดำเนินการ' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'มติ: อนุมัติให้ดำเนินการ' }).click();
  await page.getByRole('cell', { name: '/134' }).first().click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'มติ: ไม่อนุมัติ' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'มติ: ไม่อนุมัติ' }).click();
  await page.getByRole('link', { name: 'ติดตามการแก้ไขปัญหา' }).click();
  await page.getByRole('textbox', { name: 'ค้นหาเรื่องร้องเรียน, เลขที่, หรือสถานที่' }).click();
  await page.getByRole('textbox', { name: 'ค้นหาเรื่องร้องเรียน, เลขที่, หรือสถานที่' }).fill('');
  await page.getByRole('columnheader').filter({ hasText: /^$/ }).click();
  await page.getByRole('main').getByRole('button').filter({ hasText: /^$/ }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'พิมพ์เอกสารมอบหมายงาน' }).click();
  const page1 = await page1Promise;
  await page.getByText('กำลังดำเนินการ', { exact: true }).click();
  await page.getByRole('button', { name: 'บันทึกการแก้ไขเสร็จสิ้น' }).click();
  await page.getByRole('textbox', { name: 'เช่น ทำความสะอาดพื้นที่, ตรวจสอบแล้วปกติ' }).click();
  await page.getByRole('main').getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('button', { name: 'บันทึกการแก้ไขเสร็จสิ้น' }).click();
  await page.getByRole('button', { name: 'ยกเลิก' }).click();
  await page.getByRole('button', { name: 'บันทึกการแก้ไขเสร็จสิ้น' }).click();
  await page.getByRole('textbox', { name: 'เช่น ทำความสะอาดพื้นที่, ตรวจสอบแล้วปกติ' }).click();
  await page.getByRole('textbox', { name: 'เช่น ทำความสะอาดพื้นที่, ตรวจสอบแล้วปกติ' }).fill('ทำจริง');
  await page.getByRole('textbox', { name: 'เช่น 150 บาท' }).click();
  await page.getByRole('textbox', { name: 'เช่น 150 บาท' }).fill('0');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'ยืนยันปิดงาน' }).click();
});