import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    test.setTimeout(1200000); // เพิ่ม Timeout เป็น 120 วิ
    const username = `thanachot_${Date.now()}`;
    const complaintSubject = `asd_${Date.now()}`;
    await page.goto('http://localhost:3000/login');
    await page.getByRole('textbox', { name: 'ชื่อผู้ใช้งาน' }).click();
    await page.getByRole('textbox', { name: 'ชื่อผู้ใช้งาน' }).fill('admin');
    await page.getByRole('textbox', { name: 'รหัสผ่าน' }).click();
    await page.getByRole('textbox', { name: 'รหัสผ่าน' }).fill('123456');
    await page.getByRole('button', { name: 'เข้าสู่ระบบ' }).click();
    await page.locator('div').filter({ hasText: 'เรื่องทั้งหมด' }).first().click();
    await page.locator('div').filter({ hasText: 'รอดำเนินการ' }).first().click();
    await page.getByText('10').first().click();
    await page.locator('div').filter({ hasText: '1เข้าที่ประชุม' }).first().click();
    await page.getByText('5 รายการล่าสุด').first().click();
    await page.getByText('Audit log ล่าสุด').first().click();
    await page.getByText('รายการล่าสุดในระบบ').first().click();
    await page.getByRole('link', { name: 'เพิ่มบัญชีผู้ใช้งาน' }).click();
    await page.getByRole('textbox', { name: 'เช่น somchai123' }).click();
    await page.getByRole('textbox', { name: 'เช่น somchai123' }).fill(username);
    await page.getByRole('textbox', { name: 'ตั้งรหัสผ่าน 6 ตัวอักษรขึ้นไป' }).click();
    await page.getByRole('textbox', { name: 'ตั้งรหัสผ่าน 6 ตัวอักษรขึ้นไป' }).fill('123456');
    await page.locator('select[name="role"]').selectOption('staff');
    await page.locator('input[name="first_name"]').click();
    await page.locator('input[name="first_name"]').fill('ธนโชติ');
    await page.locator('input[name="last_name"]').click();
    await page.locator('input[name="last_name"]').fill('บอส');
    await page.locator('input[name="phone_number"]').click();
    await page.locator('input[name="phone_number"]').fill('0912341232');
    await page.getByRole('button', { name: 'ยืนยันการสร้างบัญชี' }).click();
    await page.waitForURL('**/admin/users');
    await page.getByRole('button', { name: 'จัดการบัญชีผู้ใช้งาน' }).click();
    await page.waitForTimeout(300); // รอให้เมนูกางเสร็จ
    await page.getByRole('link', { name: 'ปรับสิทธิ์ผู้ใช้งาน' }).click();
    await page.waitForURL(/.*\/admin\/users\?mode=roles/);
    await page.getByRole('row').filter({ hasText: `@${username}` }).getByRole('combobox').selectOption('resident');
    await page.getByRole('button', { name: 'ยืนยัน' }).click();
    await page.getByRole('link', { name: 'ลบบัญชีผู้ใช้งาน' }).click();
    await page.waitForURL(/.*\/admin\/users\?mode=delete/);
    await page.getByRole('row').filter({ hasText: `@${username}` }).getByRole('button', { name: 'ลบ' }).click();
    await page.getByRole('heading', { name: 'ยืนยันการลบบัญชี' }).click();
    const navigationPromise = page.waitForNavigation();
    await page.getByRole('button', { name: 'ลบบัญชีถาวร' }).click();
    await navigationPromise; // รอให้ระบบ reload หน้าจอเสร็จสมบูรณ์
    await page.getByRole('button', { name: 'จัดการร้องเรียน' }).click();
    await page.waitForTimeout(300); // รอให้เมนูขยาย (Animation) เสร็จก่อน
    await page.getByRole('link', { name: 'รายการร้องเรียนทั้งหมด' }).click();
    await page.getByRole('link', { name: 'สร้างคำร้องใหม่' }).click();
    await page.waitForURL('**/admin/complaints/new');
    await page.getByRole('button', { name: /83\/34/ }).first().click();
    await page.getByRole('textbox', { name: 'เช่น น้ำรั่วซึม' }).click();
    await page.getByRole('textbox', { name: 'เช่น น้ำรั่วซึม' }).fill('a');
    await page.getByRole('textbox', { name: 'อธิบายรายละเอียดปัญหา' }).click();
    await page.getByRole('textbox', { name: 'อธิบายรายละเอียดปัญหา' }).fill('a');
    await page.getByRole('textbox', { name: 'สำนักงาน' }).click();
    await page.getByRole('textbox', { name: 'สำนักงาน' }).fill('a');
    await page.getByRole('button', { name: 'บันทึกคำร้อง' }).click();
    await page.getByRole('button', { name: 'ยืนยัน' }).click();
    await page.waitForURL('**/admin/complaints');
    await page.getByRole('link', { name: 'สร้างคำร้องใหม่' }).click();
    await page.getByRole('button', { name: 'กรอกข้อมูลเอง' }).click();
    await page.getByRole('textbox', { name: 'ชื่อจริง' }).click();
    await page.getByRole('textbox', { name: 'ชื่อจริง' }).fill('ใส่ใจ');
    await page.getByRole('textbox', { name: 'นามสกุล' }).click();
    await page.getByRole('textbox', { name: 'นามสกุล' }).fill('จริง');
    await page.getByRole('textbox', { name: '08x-xxx-xxxx' }).click();
    await page.getByRole('textbox', { name: '08x-xxx-xxxx' }).fill('0912312322');
    await page.getByRole('textbox', { name: 'เช่น 88/' }).click();
    await page.getByRole('textbox', { name: 'เช่น 88/' }).fill('88/22');
    await page.getByRole('textbox', { name: 'เช่น 1,' }).click();
    await page.getByRole('textbox', { name: 'เช่น 1,' }).fill('1');
    await page.getByRole('textbox', { name: 'ซอย' }).click();
    await page.getByRole('textbox', { name: 'ซอย' }).fill('2');
    await page.locator('div').filter({ hasText: /^หัวข้อเรื่องที่ร้องเรียน \*$/ }).click();
    await page.getByRole('textbox', { name: 'เช่น น้ำรั่วซึม' }).fill(complaintSubject);
    await page.getByRole('textbox', { name: 'อธิบายรายละเอียดปัญหา' }).click();
    await page.getByRole('textbox', { name: 'อธิบายรายละเอียดปัญหา' }).fill('wasd');
    await page.getByRole('textbox', { name: 'สำนักงาน' }).click();
    await page.getByRole('textbox', { name: 'สำนักงาน' }).fill('a');
    await page.getByRole('combobox').selectOption('line');
    await page.getByRole('button', { name: 'บันทึกคำร้อง' }).click();
    await page.getByRole('button', { name: 'ยืนยัน' }).click();
    await page.waitForURL('**/admin/complaints');
    await page.getByRole('cell', { name: complaintSubject }).first().click();
    await page.getByRole('button', { name: 'อนุมัติ', exact: true }).click();
    page.once('dialog', dialog => {
        console.log(`Dialog message: ${dialog.message()}`);
        dialog.accept().catch(() => { });
    });
    await page.getByRole('button', { name: 'อัปเดตข้อมูล' }).click();
    await page.getByRole('link', { name: 'รอเข้าที่ประชุม' }).click();
    await page.waitForURL('**/admin/approvals');
    await page.getByRole('cell', { name: complaintSubject }).first().click();
    page.once('dialog', dialog => {
        console.log(`Dialog message: ${dialog.message()}`);
        dialog.accept().catch(() => { });
    });
    await page.getByRole('button', { name: 'นำเรื่องเข้าที่ประชุม' }).click();
    await page.getByRole('link', { name: 'นำเรื่องเข้าที่ประชุม' }).click();
    await page.waitForURL('**/admin/meetings');
    await page.getByRole('cell', { name: complaintSubject }).first().click();
    page.once('dialog', dialog => {
        console.log(`Dialog message: ${dialog.message()}`);
        dialog.accept().catch(() => { });
    });
    await page.getByRole('button', { name: 'มติ: อนุมัติให้ดำเนินการ' }).click();
    await page.getByRole('link', { name: 'ติดตามการแก้ไขปัญหา' }).click();
    await page.waitForURL('**/admin/maintenance');
    await page.getByRole('cell', { name: complaintSubject }).first().click();
    await page.getByRole('button', { name: 'บันทึกการแก้ไขเสร็จสิ้น' }).click();
    await page.getByRole('textbox', { name: 'เช่น ทำความสะอาดพื้นที่, ตรวจสอบแล้วปกติ' }).click();
    await page.getByRole('textbox', { name: 'เช่น ทำความสะอาดพื้นที่, ตรวจสอบแล้วปกติ' }).fill('asdfg');
    await page.getByRole('textbox', { name: 'เช่น 150 บาท' }).click();
    await page.getByRole('textbox', { name: 'เช่น 150 บาท' }).fill('455555');
    page.once('dialog', dialog => {
        console.log(`Dialog message: ${dialog.message()}`);
        dialog.accept().catch(() => { });
    });
    await page.getByRole('button', { name: 'ยืนยันปิดงาน' }).click();
    await page.getByRole('button', { name: 'จัดการร้องเรียน' }).click();
    await page.getByRole('link', { name: 'รายงานสรุป' }).click();
    await page.waitForURL('**/admin/reports');
    await page.getByText('เรื่องร้องเรียนทั้งหมด', { exact: true }).click();
    await page.getByRole('button', { name: 'ทั้งหมด' }).click();
    await page.getByRole('button', { name: 'วันนี้' }).click();
    await page.getByRole('link', { name: 'Audit Logs' }).click();
    await page.waitForURL('**/admin/logs');
    await page.getByRole('link', { name: 'โปรไฟล์' }).click();
    await page.getByRole('textbox', { name: 'กรอกรหัสผ่านใหม่ (อย่างน้อย 6' }).click();
    await page.getByRole('textbox', { name: 'กรอกรหัสผ่านใหม่ (อย่างน้อย 6' }).fill('123456');
    await page.getByRole('textbox', { name: 'กรอกรหัสผ่านใหม่อีกครั้ง' }).click();
    await page.getByRole('textbox', { name: 'กรอกรหัสผ่านใหม่อีกครั้ง' }).fill('123456');
    await page.getByRole('button', { name: 'เปลี่ยนรหัสผ่าน' }).click();
    await page.getByRole('button', { name: 'ออกจากระบบ' }).click();
    await page.getByRole('textbox', { name: 'ชื่อผู้ใช้งาน' }).click();
    await page.getByRole('textbox', { name: 'ชื่อผู้ใช้งาน' }).fill('admin');
    await page.getByRole('textbox', { name: 'รหัสผ่าน' }).click();
    await page.getByRole('textbox', { name: 'รหัสผ่าน' }).fill('123456');
    await page.getByRole('button', { name: 'เข้าสู่ระบบ' }).click();
});